### ISSUE TITLE
Pruned model need more run-time memory and time

### ISSUE THREAD

**Issue by ginger0106** [guoxiaolu/model_compression#2]
Hi, I test the pruned model Resnet50 using tensorflow profile tool and found an interesting problem that pruned model need more run-time memory and time.
std =0.8  memory=3313400812 inference-time= 96098 
std =1.0  memory=3844984812 inference-time= 107951
origin res50 memory=1768245484 inference-time=  57617
I have no idea about reason, do you have any ideas? Thanks

**Comment by guoxiaolu** [comment]
I have tested the pruned model and the inference time is about 80% cost time compared with no-pruned one. it seems impossible that cost more time as the operation and parameters are all pruned. Maybe, you should check your code when testing batch images. Besides, load model time should be removed when time calculation, and the weight h5 or initial model h5 file should be checked.

**Comment by ginger0106** [comment]
hi, I used the **tensorflow profile** tool to test the execution time, which tools you used for testing?

**Comment by guoxiaolu** [comment]
I tested it on keras(tensorflow backend) h5 file. "tensorflow profile" means tensor pb file, I have never used it.
