### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by 1448643857** [guoxiaolu/model_compression#5]
hi ,I use your code to test the inference time ,I found the time doesn't reduce,do you know the resons? 0.0

**Comment by guoxiaolu** [comment]
I have tested the pruned model and the inference time is about 80% cost time compared with no-pruned one. it seems impossible that cost more time as the operation and parameters are all pruned. Maybe, you should check your code when testing batch images. Besides, load model time should be removed when time calculation, and the weight h5 or initial model h5 file should be checked.

**Comment by 1448643857** [comment]
thank you,my test code like below:
import time
....
start = time.time()
model.predict(test_x)
end = time.time()
print(end - start)

Is right?
@guoxiaolu

**Comment by 1448643857** [comment]
> I have tested the pruned model and the inference time is about 80% cost time compared with no-pruned one. it seems impossible that cost more time as the operation and parameters are all pruned. Maybe, you should check your code when testing batch images. Besides, load model time should be removed when time calculation, and the weight h5 or initial model h5 file should be checked.

thank you,my test code like below:
import time
....
start = time.time()
model.predict(test_x)
end = time.time()
print(end - start)

Is right?
