### ISSUE TITLE
it is seem only work with keras models 

### ISSUE THREAD

**Issue by Silk760** [guoxiaolu/model_compression#7]
I tried to use alexnet model and VGG-16 on cifiar10 and show me an error, I dig to the code but without any luck of solving this issue 
<ipython-input-19-41c66e53304a> in <module>
     86 
     87 
---> 88         new_model.layers[i].set_weights(new_weight)
     89 
     90         if model_class_name == 'Sequential':

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/topology.py in set_weights(self, weights)
   1199                                  str(pv.shape) +
   1200                                  ' not compatible with '
-> 1201                                  'provided weight shape ' + str(w.shape))
   1202             weight_value_tuples.append((p, w))
   1203         K.batch_set_value(weight_value_tuples)

ValueError: Layer weight shape (3, 3, 54, 110) not compatible with provided weight shape (3, 3, 64, 110)

the model I used this one https://github.com/geifmany/cifar-vgg
but even standard alexnet show the same error but with different shape 

I hope to know what cause this problem . 

Thanks

**Comment by guoxiaolu** [comment]
It seems that your weights' input is conv2d, not Input layer. you can check vgg or resnet architecture, the input of the model is Input layer. I think this kind of given weight cannot be used in real life

**Comment by Silk760** [comment]
Thank you so much , I did what you told me to do but I still have the same issue with having the input layer 
Layer weight shape (3, 3, 42, 79) not compatible with provided weight shape (3, 3, 64, 79)

My Model configuration 

[{'class_name': 'InputLayer',
  'config': {'batch_input_shape': (None, 32, 32, 3),
   'dtype': 'float32',
   'sparse': False,
   'name': 'input_8'}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_92',
   'trainable': True,
   'filters': 64,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_113',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_106',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_78',
   'trainable': True,
   'rate': 0.3,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_93',
   'trainable': True,
   'filters': 64,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_114',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_107',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'MaxPooling2D',
  'config': {'name': 'max_pooling2d_36',
   'trainable': True,
   'pool_size': (2, 2),
   'padding': 'valid',
   'strides': (2, 2),
   'data_format': 'channels_last'}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_94',
   'trainable': True,
   'filters': 128,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_115',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_108',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_79',
   'trainable': True,
   'rate': 0.4,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_95',
   'trainable': True,
   'filters': 128,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_116',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_109',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'MaxPooling2D',
  'config': {'name': 'max_pooling2d_37',
   'trainable': True,
   'pool_size': (2, 2),
   'padding': 'valid',
   'strides': (2, 2),
   'data_format': 'channels_last'}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_96',
   'trainable': True,
   'filters': 256,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_117',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_110',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_80',
   'trainable': True,
   'rate': 0.4,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_97',
   'trainable': True,
   'filters': 256,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_118',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_111',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_81',
   'trainable': True,
   'rate': 0.4,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_98',
   'trainable': True,
   'filters': 256,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_119',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_112',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'MaxPooling2D',
  'config': {'name': 'max_pooling2d_38',
   'trainable': True,
   'pool_size': (2, 2),
   'padding': 'valid',
   'strides': (2, 2),
   'data_format': 'channels_last'}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_99',
   'trainable': True,
   'filters': 512,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_120',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_113',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_82',
   'trainable': True,
   'rate': 0.4,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_100',
   'trainable': True,
   'filters': 512,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_121',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_114',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_83',
   'trainable': True,
   'rate': 0.4,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_101',
   'trainable': True,
   'filters': 512,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_122',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_115',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'MaxPooling2D',
  'config': {'name': 'max_pooling2d_39',
   'trainable': True,
   'pool_size': (2, 2),
   'padding': 'valid',
   'strides': (2, 2),
   'data_format': 'channels_last'}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_102',
   'trainable': True,
   'filters': 512,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_123',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_116',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_84',
   'trainable': True,
   'rate': 0.4,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_103',
   'trainable': True,
   'filters': 512,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_124',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_117',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_85',
   'trainable': True,
   'rate': 0.4,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Conv2D',
  'config': {'name': 'conv2d_104',
   'trainable': True,
   'filters': 512,
   'kernel_size': (3, 3),
   'strides': (1, 1),
   'padding': 'same',
   'data_format': 'channels_last',
   'dilation_rate': (1, 1),
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_125',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_118',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'MaxPooling2D',
  'config': {'name': 'max_pooling2d_40',
   'trainable': True,
   'pool_size': (2, 2),
   'padding': 'valid',
   'strides': (2, 2),
   'data_format': 'channels_last'}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_86',
   'trainable': True,
   'rate': 0.5,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Flatten', 'config': {'name': 'flatten_8', 'trainable': True}},
 {'class_name': 'Dense',
  'config': {'name': 'dense_22',
   'trainable': True,
   'units': 4096,
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_126',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_119',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_87',
   'trainable': True,
   'rate': 0.5,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Dense',
  'config': {'name': 'dense_23',
   'trainable': True,
   'units': 4096,
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': {'class_name': 'L1L2',
    'config': {'l1': 0.0, 'l2': 0.0005000000237487257}},
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_127',
   'trainable': True,
   'activation': 'relu'}},
 {'class_name': 'BatchNormalization',
  'config': {'name': 'batch_normalization_120',
   'trainable': True,
   'axis': -1,
   'momentum': 0.99,
   'epsilon': 0.001,
   'center': True,
   'scale': True,
   'beta_initializer': {'class_name': 'Zeros', 'config': {}},
   'gamma_initializer': {'class_name': 'Ones', 'config': {}},
   'moving_mean_initializer': {'class_name': 'Zeros', 'config': {}},
   'moving_variance_initializer': {'class_name': 'Ones', 'config': {}},
   'beta_regularizer': None,
   'gamma_regularizer': None,
   'beta_constraint': None,
   'gamma_constraint': None}},
 {'class_name': 'Dropout',
  'config': {'name': 'dropout_88',
   'trainable': True,
   'rate': 0.5,
   'noise_shape': None,
   'seed': None}},
 {'class_name': 'Dense',
  'config': {'name': 'dense_24',
   'trainable': True,
   'units': 10,
   'activation': 'linear',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'kernel_regularizer': None,
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'bias_constraint': None}},
 {'class_name': 'Activation',
  'config': {'name': 'activation_128',
   'trainable': True,
   'activation': 'softmax'}}]

**Comment by guoxiaolu** [comment]
can you provide the model or just print model.summary()?
